name: civic_data_warehouse
version: "1.0.0"
config-version: 2

profile: civic_data_warehouse

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  civic_data_warehouse:
    +materialized: table
    current:
      +schema: current
    staging:
      +schema: staging_dbt
      +materialized: view
    examples:
      +enabled: false
