FROM quay.io/astronomer/astro-runtime:7.4.2

ENV AWS_ACCESS_KEY_ID="<aws_access_key>"
ENV AWS_SECRET_ACCESS_KEY="<aws_secret_key>"
ENV AWS_DEFAULT_REGION=us-east-1
ENV AIRFLOW__SECRETS__BACKEND="airflow.contrib.secrets.aws_systems_manager.SystemsManagerParameterStoreBackend"
ENV AIRFLOW__SECRETS__BACKEND_KWARGS='{"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables"}'