version: 2

sources:
  - name: staging
    schema: staging
    tables:
      - name: bincode_cdbinccecode
      - name: bincode_cdbininsptype
      - name: bincode_cdbinroomtype
      - name: bincode_cdbinsectioncode
      - name: bincode_cdfineownertype
      - name: bincode_cdorigltrsource
      - name: bincode_cdorigltrtype
      - name: bincode_cdvioldegree
      - name: building_permits_last_30_days
      - name: cndcode_cdcndimpactcode
      - name: cndcode_cdcndinsptype
      - name: cndcode_cdcndstatus
      - name: cndcodes
      - name: comcode_cdaddrsourcelevel
      - name: comcode_cdald
      - name: comcode_cdfaceerr
      - name: comcode_cdnlcerr
      - name: comcode_cdprclerr
      - name: condemn
      - name: corcode_cdabbrfulltext
      - name: corcode_cdabbrspectype
      - name: corcode_cdabbrtype
      - name: corcode_cdaltnlctype
      - name: corcode_cdavcodes
      - name: corcode_cdblockdeltype
      - name: corcode_cdblockoldsrc
      - name: corcode_cdblockspectype
      - name: corcode_cdblocksuf
      - name: corcode_cdcdasubdist
      - name: corcode_cdcorsyserr
      - name: corcode_cdentzone
      - name: corcode_cdgeoabbr
      - name: corcode_cdhcd
      - name: corcode_cdintaddrtype
      - name: corcode_cdleafarea
      - name: corcode_cdnbrhd
      - name: corcode_cdnlctype
      - name: corcode_cdobblitzregion
      - name: corcode_cdrngrank
      - name: corcode_cdspecusedist
      - name: corcode_cdstclass
      - name: corcode_cdstdirtype
      - name: corcode_cdstjurisdiction
      - name: corcode_cdtrafdist
      - name: corcode_cdtrbulkregion
      - name: corcode_cdtrcontainarea
      - name: corcode_cdtrrolloutarea
      - name: demolition_permits_last_30_days
      - name: electrical_permits_last_30_days
      - name: forestry_maintenance_properties
      - name: hcd_hcddate
      - name: hcd_hcdinsp
      - name: lra_public_dbo_vw_boardup_public
      - name: lra_public_dbo_vw_public_inventory
      - name: mechanical_permits_last_30_days
      - name: occupancy_permits_last_30_days
      - name: plumbing_permits_last_30_days
      - name: prcl_bldgall
      - name: prcl_bldgcom
      - name: prcl_bldgres
      - name: prcl_bldgresimp
      - name: prcl_bldgsect
      - name: prcl_cdattrtypenum
      - name: prcl_cxprclcnblk10
      - name: prcl_cxprclcnblk20
      - name: prcl_prcl
      - name: prcl_prcladdr
      - name: prcl_prcladdrlrms
      - name: prcl_prclasmt
      - name: prcl_prclattr
      - name: prcl_prclattrasr
      - name: prcl_prcldate
      - name: prcl_prclimp
      - name: prcl_prclrear
      - name: prcl_prclsbd
      - name: prclcode_cdaddrtype
      - name: prclcode_cdasmtappealtype
      - name: prclcode_cdasrclasscode
      - name: prclcode_cdattrignorecode
      - name: prclcode_cdattrtype
      - name: prclcode_cdattrtypenum
      - name: prclcode_cdattrxboundarycode
      - name: prclcode_cdbadaddrtype
      - name: prclcode_cdbsmtfinish
      - name: prclcode_cdbsmttype
      - name: prclcode_cdcitylanddist
      - name: prclcode_cdcitylandmark
      - name: prclcode_cdcomcategory
      - name: prclcode_cdcomconsttype
      - name: prclcode_cdcomextwall
      - name: prclcode_cdcomstories
      - name: prclcode_cdcomtype
      - name: prclcode_cdcomunitplan
      - name: prclcode_cdfbdnum
      - name: prclcode_cdlanduse
      - name: prclcode_cdlocalcertdist
      - name: prclcode_cdlocalhistdist
      - name: prclcode_cdnathistdist
      - name: prclcode_cdnatlandmark
      - name: prclcode_cdnatregister
      - name: prclcode_cdownercode
      - name: prclcode_cdownerocccode
      - name: prclcode_cdprclsource
      - name: prclcode_cdprimaddrmisscode
      - name: prclcode_cdrearcomrescode
      - name: prclcode_cdresextwall
      - name: prclcode_cdresmodel
      - name: prclcode_cdresmodeladj
      - name: prclcode_cdresocc
      - name: prclcode_cdressalesource
      - name: prclcode_cdresstories
      - name: prclcode_cdsaletype
      - name: prclcode_cdspecbusdist
      - name: prclcode_cdspecparceltype
      - name: prclcode_cdspecusedist
      - name: prclcode_cdsubparceltype
      - name: prclcode_cdtifdist
      - name: prclcode_cdzoning
      - name: prclcode_cdzoninglrms
      - name: prclcode_cxownergroup
      - name: prclsale_cdcityblockpartsrc
      - name: prclsale_cdsaletype
      - name: prclsale_histprclsale
      - name: prclsale_prclsale
